variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
name: $(date:yyyyMMdd)$(rev:.r)
trigger:
  branches:
    include:
    - develop
jobs:
- job: Phase_1
  displayName: Phase 1
  cancelTimeoutInMinutes: 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/$safeprojectname$.Console.csproj'
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      projects: '**/$safeprojectname$.Console.csproj'
      arguments: -r win-x64 --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --self-contained true
      zipAfterPublish: True
      publishWebProjects: false
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'