// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using $ext_safeprojectname$.DataAccess.EF;
using $ext_safeprojectname$.DataAccess.EF.Oracle.DbContext;
using $ext_safeprojectname$.DataAccess.EF.Oracle.Entities;

#nullable disable

namespace $ext_safeprojectname$.DataAccess.EF.Oracle.DbContext.Configurations
{
    public partial class SapMaraConfiguration : IEntityTypeConfiguration<SapMara>
    {
        public void Configure(EntityTypeBuilder<SapMara> entity)
        {
            entity.HasKey(e => e.Matnr)
                .HasName("SAP_MARA_PK01");

            entity.Property(e => e.Matnr).IsUnicode(false);

            entity.Property(e => e.Adprof).IsUnicode(false);

            entity.Property(e => e.Aenam).IsUnicode(false);

            entity.Property(e => e.Aeszn).IsUnicode(false);

            entity.Property(e => e.AllowPmatIgno).IsUnicode(false);

            entity.Property(e => e.Attyp).IsUnicode(false);

            entity.Property(e => e.Begru).IsUnicode(false);

            entity.Property(e => e.Behvo).IsUnicode(false);

            entity.Property(e => e.Bismt).IsUnicode(false);

            entity.Property(e => e.Blanz).IsUnicode(false);

            entity.Property(e => e.Blatt).IsUnicode(false);

            entity.Property(e => e.BrandId).IsUnicode(false);

            entity.Property(e => e.Breit).IsUnicode(false);

            entity.Property(e => e.Brgew).IsUnicode(false);

            entity.Property(e => e.Bstat).IsUnicode(false);

            entity.Property(e => e.Bstme).IsUnicode(false);

            entity.Property(e => e.Bwscl).IsUnicode(false);

            entity.Property(e => e.Bwvor).IsUnicode(false);

            entity.Property(e => e.Cadkz).IsUnicode(false);

            entity.Property(e => e.CareCode).IsUnicode(false);

            entity.Property(e => e.Datab).IsUnicode(false);

            entity.Property(e => e.Ean11).IsUnicode(false);

            entity.Property(e => e.Ekwsl).IsUnicode(false);

            entity.Property(e => e.Ergei).IsUnicode(false);

            entity.Property(e => e.Ergew).IsUnicode(false);

            entity.Property(e => e.Ernam).IsUnicode(false);

            entity.Property(e => e.Ersda).IsUnicode(false);

            entity.Property(e => e.Ervoe).IsUnicode(false);

            entity.Property(e => e.Ervol).IsUnicode(false);

            entity.Property(e => e.Etiar).IsUnicode(false);

            entity.Property(e => e.Etifo).IsUnicode(false);

            entity.Property(e => e.Extwg).IsUnicode(false);

            entity.Property(e => e.Fashgrd).IsUnicode(false);

            entity.Property(e => e.Ferth).IsUnicode(false);

            entity.Property(e => e.FiberCode1).IsUnicode(false);

            entity.Property(e => e.FiberCode2).IsUnicode(false);

            entity.Property(e => e.FiberCode3).IsUnicode(false);

            entity.Property(e => e.FiberCode4).IsUnicode(false);

            entity.Property(e => e.FiberCode5).IsUnicode(false);

            entity.Property(e => e.FiberPart1).IsUnicode(false);

            entity.Property(e => e.FiberPart2).IsUnicode(false);

            entity.Property(e => e.FiberPart3).IsUnicode(false);

            entity.Property(e => e.FiberPart4).IsUnicode(false);

            entity.Property(e => e.FiberPart5).IsUnicode(false);

            entity.Property(e => e.Formt).IsUnicode(false);

            entity.Property(e => e.FreeChar).IsUnicode(false);

            entity.Property(e => e.Fuelg).IsUnicode(false);

            entity.Property(e => e.Gennr).IsUnicode(false);

            entity.Property(e => e.Gewei).IsUnicode(false);

            entity.Property(e => e.Gewto).IsUnicode(false);

            entity.Property(e => e.Groes).IsUnicode(false);

            entity.Property(e => e.Hazmat).IsUnicode(false);

            entity.Property(e => e.Herkl).IsUnicode(false);

            entity.Property(e => e.Hndlcode).IsUnicode(false);

            entity.Property(e => e.Hoehe).IsUnicode(false);

            entity.Property(e => e.Hutyp).IsUnicode(false);

            entity.Property(e => e.HutypDflt).IsUnicode(false);

            entity.Property(e => e.Ihivi).IsUnicode(false);

            entity.Property(e => e.Iloos).IsUnicode(false);

            entity.Property(e => e.Inhal).IsUnicode(false);

            entity.Property(e => e.Inhbr).IsUnicode(false);

            entity.Property(e => e.Inhme).IsUnicode(false);

            entity.Property(e => e.Iprkz).IsUnicode(false);

            entity.Property(e => e.Isvalid)
                .HasPrecision(1)
                .HasComputedColumnSql("CASE  WHEN (LENGTH(TRIM(\"ZZ_PLMID\"))=8 AND LENGTH(TRIM(\"PRDHA\"))=12) THEN 1 ELSE 0 END ", false);

            entity.Property(e => e.Kosch).IsUnicode(false);

            entity.Property(e => e.Kunnr).IsUnicode(false);

            entity.Property(e => e.Kzgvh).IsUnicode(false);

            entity.Property(e => e.Kzumw).IsUnicode(false);

            entity.Property(e => e.Labor).IsUnicode(false);

            entity.Property(e => e.Laeda).IsUnicode(false);

            entity.Property(e => e.Laeng).IsUnicode(false);

            entity.Property(e => e.Liqdt).IsUnicode(false);

            entity.Property(e => e.Lvorm).IsUnicode(false);

            entity.Property(e => e.Magrv).IsUnicode(false);

            entity.Property(e => e.Mandt).IsUnicode(false);

            entity.Property(e => e.Matkl).IsUnicode(false);

            entity.Property(e => e.Maxb).IsUnicode(false);

            entity.Property(e => e.Maxc).IsUnicode(false);

            entity.Property(e => e.MaxcTol).IsUnicode(false);

            entity.Property(e => e.MaxdimUom).IsUnicode(false);

            entity.Property(e => e.Maxh).IsUnicode(false);

            entity.Property(e => e.Maxl).IsUnicode(false);

            entity.Property(e => e.Meabm).IsUnicode(false);

            entity.Property(e => e.Meins).IsUnicode(false);

            entity.Property(e => e.Mfrgr).IsUnicode(false);

            entity.Property(e => e.Mhdhb).IsUnicode(false);

            entity.Property(e => e.Mhdlp).IsUnicode(false);

            entity.Property(e => e.Mhdrz).IsUnicode(false);

            entity.Property(e => e.Mlgut).IsUnicode(false);

            entity.Property(e => e.Mstae).IsUnicode(false);

            entity.Property(e => e.Mstav).IsUnicode(false);

            entity.Property(e => e.Mstde).IsUnicode(false);

            entity.Property(e => e.Mstdv).IsUnicode(false);

            entity.Property(e => e.Mtart).IsUnicode(false);

            entity.Property(e => e.MtposMara).IsUnicode(false);

            entity.Property(e => e.Normt).IsUnicode(false);

            entity.Property(e => e.Nrfhg).IsUnicode(false);

            entity.Property(e => e.Ntgew).IsUnicode(false);

            entity.Property(e => e.Numtp).IsUnicode(false);

            entity.Property(e => e.Pilferable).IsUnicode(false);

            entity.Property(e => e.Plgtp).IsUnicode(false);

            entity.Property(e => e.Pmata).IsUnicode(false);

            entity.Property(e => e.Prdha).IsUnicode(false);

            entity.Property(e => e.Profl).IsUnicode(false);

            entity.Property(e => e.Przus).IsUnicode(false);

            entity.Property(e => e.PsSmartform).IsUnicode(false);

            entity.Property(e => e.Qgrp).IsUnicode(false);

            entity.Property(e => e.Qmpur).IsUnicode(false);

            entity.Property(e => e.Qqtime).IsUnicode(false);

            entity.Property(e => e.Qqtimeuom).IsUnicode(false);

            entity.Property(e => e.Raube).IsUnicode(false);

            entity.Property(e => e.Rbnrm).IsUnicode(false);

            entity.Property(e => e.Rdmhd).IsUnicode(false);

            entity.Property(e => e.Rmatp).IsUnicode(false);

            entity.Property(e => e.Saisj).IsUnicode(false);

            entity.Property(e => e.Saiso).IsUnicode(false);

            entity.Property(e => e.Saity).IsUnicode(false);

            entity.Property(e => e.Satnr).IsUnicode(false);

            entity.Property(e => e.Serial).IsUnicode(false);

            entity.Property(e => e.Spart).IsUnicode(false);

            entity.Property(e => e.Sprof).IsUnicode(false);

            entity.Property(e => e.Stfak).IsUnicode(false);

            entity.Property(e => e.Stoff).IsUnicode(false);

            entity.Property(e => e.Taklv).IsUnicode(false);

            entity.Property(e => e.TareVar).IsUnicode(false);

            entity.Property(e => e.Tempb).IsUnicode(false);

            entity.Property(e => e.Tragr).IsUnicode(false);

            entity.Property(e => e.Vabme).IsUnicode(false);

            entity.Property(e => e.Vhart).IsUnicode(false);

            entity.Property(e => e.Voleh).IsUnicode(false);

            entity.Property(e => e.Volto).IsUnicode(false);

            entity.Property(e => e.Volum).IsUnicode(false);

            entity.Property(e => e.Vpreh).IsUnicode(false);

            entity.Property(e => e.Wesch).IsUnicode(false);

            entity.Property(e => e.Whmatgr).IsUnicode(false);

            entity.Property(e => e.Whstc).IsUnicode(false);

            entity.Property(e => e.Wrkst).IsUnicode(false);

            entity.Property(e => e.Xchpf).IsUnicode(false);

            entity.Property(e => e.Xgchp).IsUnicode(false);

            entity.Property(e => e.Zeiar).IsUnicode(false);

            entity.Property(e => e.Zeifo).IsUnicode(false);

            entity.Property(e => e.Zeinr).IsUnicode(false);

            entity.Property(e => e.Zeivr).IsUnicode(false);

            entity.Property(e => e.ZzChoice).IsUnicode(false);

            entity.Property(e => e.ZzChoiceid).IsUnicode(false);

            entity.Property(e => e.ZzChoiceid1).IsUnicode(false);

            entity.Property(e => e.ZzClear).IsUnicode(false);

            entity.Property(e => e.ZzDiscon).IsUnicode(false);

            entity.Property(e => e.ZzDisconfl).IsUnicode(false);

            entity.Property(e => e.ZzEmbel).IsUnicode(false);

            entity.Property(e => e.ZzEmdial).IsUnicode(false);

            entity.Property(e => e.ZzHazmwei).IsUnicode(false);

            entity.Property(e => e.ZzLongsku).IsUnicode(false);

            entity.Property(e => e.ZzPlanstat).IsUnicode(false);

            entity.Property(e => e.ZzPlmid).IsUnicode(false);

            entity.Property(e => e.ZzPlmidchoice).IsUnicode(false);

            entity.Property(e => e.ZzPromo).IsUnicode(false);

            entity.Property(e => e.ZzPrprom).IsUnicode(false);

            entity.Property(e => e.ZzPset).IsUnicode(false);

            entity.Property(e => e.ZzSectag).IsUnicode(false);

            entity.Property(e => e.ZzSharef).IsUnicode(false);

            entity.Property(e => e.ZzSteam).IsUnicode(false);

            entity.Property(e => e.ZzStyle).IsUnicode(false);

            entity.Property(e => e.ZzStyleid).IsUnicode(false);

            entity.Property(e => e.ZzStyleid1).IsUnicode(false);

            entity.Property(e => e.ZzSubclass).IsUnicode(false);

            entity.Property(e => e.ZzSubclass1).IsUnicode(false);

            entity.Property(e => e.ZzSubrand).IsUnicode(false);

            entity.Property(e => e.ZzSubrand1).IsUnicode(false);

            entity.Property(e => e.ZzTest).IsUnicode(false);

            entity.Property(e => e.ZzTrack).IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SapMara> entity);
    }
}
