// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using $ext_safeprojectname$.DataAccess.EF;
using $ext_safeprojectname$.DataAccess.EF.Sql.DbContext;
using $ext_safeprojectname$.DataAccess.EF.Sql.Entities;

#nullable disable

namespace $ext_safeprojectname$.DataAccess.EF.Sql.DbContext.Configurations
{
    public partial class EpUsersConfiguration : IEntityTypeConfiguration<EpUsers>
    {
        public void Configure(EntityTypeBuilder<EpUsers> entity)
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

            entity.Property(e => e.Active).HasDefaultValueSql("((1))");

            entity.Property(e => e.CreateDate).HasDefaultValueSql("((sysdatetimeoffset() AT TIME ZONE 'Eastern Standard Time'))");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EpUsers> entity);
    }
}
