// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using $ext_safeprojectname$.DataAccess.EF;
using $ext_safeprojectname$.DataAccess.EF.Sql.DbContext;
using $ext_safeprojectname$.DataAccess.EF.Sql.Entities;

#nullable disable

namespace $ext_safeprojectname$.DataAccess.EF.Sql.DbContext.Configurations
{
    public partial class VsEpConfigurationConfiguration : IEntityTypeConfiguration<VsEpConfiguration>
    {
        public void Configure(EntityTypeBuilder<VsEpConfiguration> entity)
        {
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Description).IsFixedLength();

            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VsEpConfiguration> entity);
    }
}
