// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using $ext_safeprojectname$.DataAccess.EF;
using $ext_safeprojectname$.DataAccess.EF.Sql.DbContext;
using $ext_safeprojectname$.DataAccess.EF.Sql.Entities;

#nullable disable

namespace $ext_safeprojectname$.DataAccess.EF.Sql.DbContext.Configurations
{
    public partial class VwAllocationFeedConfiguration : IEntityTypeConfiguration<VwAllocationFeed>
    {
        public void Configure(EntityTypeBuilder<VwAllocationFeed> entity)
        {
            entity.ToView("vw_Allocation_Feed");

            entity.Property(e => e.OrganizationName).IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwAllocationFeed> entity);
    }
}
